---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-majkulator-view
data:
  ASPNETCORE_ENVIRONMENT: "{{ .Values.aspNetCoreEnv }}"
  EF_MIGRATE: "{{ .Values.efMigrate }}"
  
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-majkulator-view
type: Opaque
data:
  CONNECTIONSTRINGS__CONTEXT: {{ "Server=aronia-postgresql;Port=5432;Database=aronia;User Id=test;Password=test;" | b64enc }}
