apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-frontend
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - {{ .Release.Name }}-frontend.{{ .Release.Namespace }}.{{ .Values.global.domain }}
      secretName: {{ .Release.Name }}-frontend.{{ .Release.Namespace }}.{{ .Values.global.domain }}-tls
  rules:
    - host: {{ .Release.Name }}-frontend.{{ .Release.Namespace }}.{{ .Values.global.domain }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-frontend
                port:
                  number: 80
                