apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Release.Name }}-frontend
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: frontend=jurajpaska8/majkulator
    argocd-image-updater.argoproj.io/write-back-method: git
spec:
  source:
    path:{{ "helm" | quote }}
    repoURL:{{ "https://github.com/jurajpaska8/majkulator-deploy.git" | quote }}
